### ISSUE TITLE
Integrate this into react-navigation?

### ISSUE THREAD

**Issue by ghost** [jonsamp/react-native-header-scroll-view#2]
Great component! This is the most highly requested features of the community for @react-navigation. Starting this issue to see if integration is possible.

iOS large title FR from Canny: https://react-navigation.canny.io/feature-requests/p/ios-11-large-header-and-growshrink-on-scroll
React Navigation: https://github.com/react-navigation/react-navigation

**Comment by ghost** [comment]
React Navigation Contributing Guidelines: https://reactnavigation.org/docs/en/contributing.html

**Comment by jonsamp** [comment]
@thomaswangio thanks for the issue and for nominating this package.

Closing this ticket bc your PR was merged. Noting some links for posterity:

Twitter discussion: https://twitter.com/thomaswangio/status/1179164439884386304?s=20
PR: https://github.com/react-navigation/react-navigation.github.io/pull/533/files
Link in react-navigation docs: https://reactnavigation.org/docs/en/next/community-libraries-and-navigators.html
